# String in format 1s2m3h
interval = '1s' # 1 second

[predicates]

[predicates.by-name]
verbatim = [
    'MicrosoftEdgeUpdate.exe',
    'GoogleUpdate.exe'
]
regex-patterns = []
glob-patterns = []

[ignores]

[ignores.by-name]
verbatim = []
regex-patterns = []
glob-patterns = []
